#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zsh/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zsh/init.zsh"
fi

# Customize to your needs...

#need to override, else cursor is disapearing when moved around
ZSH_HIGHLIGHT_STYLES[cursor]='bg=grey'
ZSH_HIGHLIGHT_STYLES[globbing]='fg=cyan'

source "${ZDOTDIR:-$HOME}/.zsh/rc.local"

